# docker-compose.host.yml
#
# Use this file ONLY on Linux hosts. It configures the services to use
# host networking (network_mode: host) so containers share the host
# network namespace and can reach services on localhost:PORT.
#
# WARNING: host networking is not supported on macOS or Windows with
# Docker Desktop in the same way; on those platforms this file WILL NOT
# behave as expected. Prefer the default docker-compose.yml on macOS/Win.

version: '3.8'

services:
  server:
    build:
      context: ./guidance-application
      dockerfile: dockerfile
    image: guidance-server:host
    container_name: server-host
    restart: unless-stopped
    network_mode: host
    volumes:
      - guidance-data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

  client:
    build:
      context: ./guidance-client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:5000
    image: guidance-client:host
    container_name: client-host
    restart: unless-stopped
    network_mode: host
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000

volumes:
  guidance-data:
